import type { Metadata } from "next";
import { Box } from "@mui/material";
import { performRequest } from "@/lib/datocms";
import { GET_HOME } from "@/graphql/homeQuery";
import { GET_SEO } from "@/graphql/seoQuery";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seoData = await performRequest<any>(GET_SEO);
  const homeData = await performRequest<any>(GET_HOME);

  const seo: any = seoData;
  const home: any = homeData.allHomePages[0];
  return (
    <Box>
      {home && <Navbar logo={home.logo} />}
      {children}
    </Box>
  );
}
