import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { SettingProvider } from "@/components/setting/setting-provider";
import ThemProvider from "@/components/theme-provider";
import PrimarySearchAppBar from "@/components/app-bar";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <SettingProvider>
            <ThemProvider>
              <Container maxWidth={false} disableGutters>
                <PrimarySearchAppBar />
                {children}
              </Container>
            </ThemProvider>
          </SettingProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
