import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { SettingProvider } from "@/components/setting/setting-provider";
import ThemProvider from "@/components/theme-provider";
import { Container } from "@mui/material";
import TanstackProvider from "@/utits/tanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <TanstackProvider>
            <SettingProvider>
              <ThemProvider>
                <Container maxWidth={false} disableGutters>
                  {children}
                </Container>
              </ThemProvider>
            </SettingProvider>
          </TanstackProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
